/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 134
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 3
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 18
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 24
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_LBRACE = 2,
  anon_sym_LF = 3,
  anon_sym_CR_LF = 4,
  anon_sym_SEMI = 5,
  anon_sym_RBRACE = 6,
  sym_identifier = 7,
  anon_sym_EQ = 8,
  anon_sym_BANG_EQ = 9,
  anon_sym_TILDE = 10,
  sym_unescaped_single_string_fragment = 11,
  sym_escape_sequence = 12,
  anon_sym_let = 13,
  anon_sym_inheriting = 14,
  anon_sym_matching = 15,
  anon_sym_COMMA = 16,
  anon_sym_COLON = 17,
  anon_sym_SQUOTE = 18,
  anon_sym_DOT = 19,
  anon_sym_fn = 20,
  anon_sym_LPAREN = 21,
  anon_sym_RPAREN = 22,
  anon_sym_not = 23,
  anon_sym_AMP_AMP = 24,
  anon_sym_PIPE_PIPE = 25,
  sym_universal_selector = 26,
  anon_sym_GT = 27,
  anon_sym_LBRACK = 28,
  anon_sym_RBRACK = 29,
  sym_source_file = 30,
  sym_query = 31,
  sym_attribute_relation = 32,
  sym_lexical_binding = 33,
  sym_lexical_binding_inheritance = 34,
  sym_variable_declarator = 35,
  sym_object_pattern = 36,
  sym_pair_pattern = 37,
  sym_string_literal = 38,
  sym__expression = 39,
  sym_attribute_identifier = 40,
  sym_function_declaration = 41,
  sym_function_call = 42,
  sym_function_match = 43,
  sym_condition = 44,
  sym__condition = 45,
  sym_and_condition = 46,
  sym_or_condition = 47,
  sym_attribute_condition = 48,
  sym__selector = 49,
  sym_child_selector = 50,
  sym_attribute_selector = 51,
  aux_sym_source_file_repeat1 = 52,
  aux_sym_query_repeat1 = 53,
  aux_sym_object_pattern_repeat1 = 54,
  aux_sym_string_literal_repeat1 = 55,
  aux_sym_function_declaration_repeat1 = 56,
  aux_sym_function_declaration_repeat2 = 57,
  aux_sym_function_call_repeat1 = 58,
  alias_sym_function_parameter = 59,
  alias_sym_node_kind_identifier = 60,
  alias_sym_variable = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_LBRACE] = "{",
  [anon_sym_LF] = "\n",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_SEMI] = ";",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_TILDE] = "~",
  [sym_unescaped_single_string_fragment] = "string_fragment",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_let] = "let",
  [anon_sym_inheriting] = "inheriting",
  [anon_sym_matching] = "matching",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DOT] = ".",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_not] = "not",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [sym_universal_selector] = "universal_selector",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym_query] = "query",
  [sym_attribute_relation] = "attribute_relation",
  [sym_lexical_binding] = "lexical_binding",
  [sym_lexical_binding_inheritance] = "lexical_binding_inheritance",
  [sym_variable_declarator] = "variable_declarator",
  [sym_object_pattern] = "object_pattern",
  [sym_pair_pattern] = "pair_pattern",
  [sym_string_literal] = "string_literal",
  [sym__expression] = "_expression",
  [sym_attribute_identifier] = "attribute_identifier",
  [sym_function_declaration] = "function_declaration",
  [sym_function_call] = "function_call",
  [sym_function_match] = "function_match",
  [sym_condition] = "condition",
  [sym__condition] = "_condition",
  [sym_and_condition] = "and_condition",
  [sym_or_condition] = "or_condition",
  [sym_attribute_condition] = "attribute_condition",
  [sym__selector] = "_selector",
  [sym_child_selector] = "child_selector",
  [sym_attribute_selector] = "attribute_selector",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_query_repeat1] = "query_repeat1",
  [aux_sym_object_pattern_repeat1] = "object_pattern_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
  [aux_sym_function_declaration_repeat1] = "function_declaration_repeat1",
  [aux_sym_function_declaration_repeat2] = "function_declaration_repeat2",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [alias_sym_function_parameter] = "function_parameter",
  [alias_sym_node_kind_identifier] = "node_kind_identifier",
  [alias_sym_variable] = "variable",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [sym_unescaped_single_string_fragment] = sym_unescaped_single_string_fragment,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_inheriting] = anon_sym_inheriting,
  [anon_sym_matching] = anon_sym_matching,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [sym_universal_selector] = sym_universal_selector,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym_query] = sym_query,
  [sym_attribute_relation] = sym_attribute_relation,
  [sym_lexical_binding] = sym_lexical_binding,
  [sym_lexical_binding_inheritance] = sym_lexical_binding_inheritance,
  [sym_variable_declarator] = sym_variable_declarator,
  [sym_object_pattern] = sym_object_pattern,
  [sym_pair_pattern] = sym_pair_pattern,
  [sym_string_literal] = sym_string_literal,
  [sym__expression] = sym__expression,
  [sym_attribute_identifier] = sym_attribute_identifier,
  [sym_function_declaration] = sym_function_declaration,
  [sym_function_call] = sym_function_call,
  [sym_function_match] = sym_function_match,
  [sym_condition] = sym_condition,
  [sym__condition] = sym__condition,
  [sym_and_condition] = sym_and_condition,
  [sym_or_condition] = sym_or_condition,
  [sym_attribute_condition] = sym_attribute_condition,
  [sym__selector] = sym__selector,
  [sym_child_selector] = sym_child_selector,
  [sym_attribute_selector] = sym_attribute_selector,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_query_repeat1] = aux_sym_query_repeat1,
  [aux_sym_object_pattern_repeat1] = aux_sym_object_pattern_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
  [aux_sym_function_declaration_repeat1] = aux_sym_function_declaration_repeat1,
  [aux_sym_function_declaration_repeat2] = aux_sym_function_declaration_repeat2,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [alias_sym_function_parameter] = alias_sym_function_parameter,
  [alias_sym_node_kind_identifier] = alias_sym_node_kind_identifier,
  [alias_sym_variable] = alias_sym_variable,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [sym_unescaped_single_string_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_inheriting] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_matching] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_universal_selector] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_relation] = {
    .visible = true,
    .named = true,
  },
  [sym_lexical_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_lexical_binding_inheritance] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_declarator] = {
    .visible = true,
    .named = true,
  },
  [sym_object_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_pair_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_attribute_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_function_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_function_match] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym__condition] = {
    .visible = false,
    .named = true,
  },
  [sym_and_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_or_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_condition] = {
    .visible = true,
    .named = true,
  },
  [sym__selector] = {
    .visible = false,
    .named = true,
  },
  [sym_child_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_selector] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_declaration_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_function_parameter] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_node_kind_identifier] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_variable] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_arguments = 1,
  field_child = 2,
  field_condition = 3,
  field_condition_1 = 4,
  field_condition_2 = 5,
  field_content = 6,
  field_expression_1 = 7,
  field_expression_2 = 8,
  field_function = 9,
  field_identifier = 10,
  field_key = 11,
  field_name = 12,
  field_parameters = 13,
  field_parent = 14,
  field_relation = 15,
  field_selector = 16,
  field_statement = 17,
  field_value = 18,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arguments] = "arguments",
  [field_child] = "child",
  [field_condition] = "condition",
  [field_condition_1] = "condition_1",
  [field_condition_2] = "condition_2",
  [field_content] = "content",
  [field_expression_1] = "expression_1",
  [field_expression_2] = "expression_2",
  [field_function] = "function",
  [field_identifier] = "identifier",
  [field_key] = "key",
  [field_name] = "name",
  [field_parameters] = "parameters",
  [field_parent] = "parent",
  [field_relation] = "relation",
  [field_selector] = "selector",
  [field_statement] = "statement",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [4] = {.index = 1, .length = 1},
  [5] = {.index = 2, .length = 2},
  [6] = {.index = 4, .length = 1},
  [7] = {.index = 5, .length = 1},
  [8] = {.index = 6, .length = 2},
  [9] = {.index = 8, .length = 2},
  [10] = {.index = 10, .length = 2},
  [11] = {.index = 12, .length = 1},
  [12] = {.index = 13, .length = 1},
  [13] = {.index = 14, .length = 3},
  [14] = {.index = 17, .length = 2},
  [16] = {.index = 19, .length = 1},
  [17] = {.index = 20, .length = 2},
  [18] = {.index = 22, .length = 2},
  [19] = {.index = 24, .length = 1},
  [20] = {.index = 25, .length = 2},
  [21] = {.index = 27, .length = 3},
  [22] = {.index = 30, .length = 2},
  [23] = {.index = 32, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_selector, 0},
  [1] =
    {field_condition, 0},
  [2] =
    {field_child, 2},
    {field_parent, 0},
  [4] =
    {field_statement, 0},
  [5] =
    {field_identifier, 1},
  [6] =
    {field_selector, 0},
    {field_statement, 2, .inherited = true},
  [8] =
    {field_statement, 0, .inherited = true},
    {field_statement, 1, .inherited = true},
  [10] =
    {field_condition, 2},
    {field_selector, 0},
  [12] =
    {field_name, 0},
  [13] =
    {field_content, 1},
  [14] =
    {field_expression_1, 0},
    {field_expression_2, 2},
    {field_relation, 1},
  [17] =
    {field_condition_1, 0},
    {field_condition_2, 2},
  [19] =
    {field_name, 1},
  [20] =
    {field_arguments, 2},
    {field_name, 0},
  [22] =
    {field_identifier, 1},
    {field_value, 3},
  [24] =
    {field_function, 3},
  [25] =
    {field_name, 1},
    {field_parameters, 3},
  [27] =
    {field_arguments, 2},
    {field_arguments, 3},
    {field_name, 0},
  [30] =
    {field_key, 0},
    {field_value, 2},
  [32] =
    {field_name, 1},
    {field_parameters, 3},
    {field_parameters, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_node_kind_identifier,
  },
  [3] = {
    [0] = alias_sym_variable,
  },
  [15] = {
    [1] = alias_sym_function_parameter,
  },
  [20] = {
    [3] = alias_sym_function_parameter,
  },
  [23] = {
    [3] = alias_sym_function_parameter,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 3,
  [8] = 2,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 11,
  [15] = 10,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 20,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 39,
  [40] = 19,
  [41] = 33,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 32,
  [46] = 28,
  [47] = 47,
  [48] = 31,
  [49] = 49,
  [50] = 23,
  [51] = 27,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 54,
  [67] = 55,
  [68] = 57,
  [69] = 58,
  [70] = 65,
  [71] = 61,
  [72] = 63,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 42,
  [88] = 88,
  [89] = 49,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 42,
  [94] = 49,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 74,
  [100] = 100,
  [101] = 97,
  [102] = 76,
  [103] = 103,
  [104] = 100,
  [105] = 100,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 123,
  [132] = 132,
  [133] = 133,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        '!', 8,
        '&', 2,
        '\'', 71,
        '(', 74,
        ')', 75,
        '*', 79,
        ',', 69,
        '-', 7,
        '.', 72,
        ':', 70,
        ';', 31,
        '=', 56,
        '>', 80,
        '[', 81,
        '\\', 17,
        ']', 82,
        'f', 44,
        'i', 45,
        'l', 35,
        'm', 33,
        'n', 48,
        '{', 29,
        '|', 19,
        '}', 32,
        '~', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '&') ADVANCE(2);
      if (lookahead == '(') ADVANCE(74);
      if (lookahead == ';') ADVANCE(31);
      if (lookahead == '|') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '&') ADVANCE(77);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '(') ADVANCE(74);
      if (lookahead == ')') ADVANCE(75);
      if (lookahead == '*') ADVANCE(79);
      if (lookahead == '.') ADVANCE(72);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead == '}') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\'', 71,
        '(', 74,
        '*', 79,
        '-', 7,
        '.', 72,
        'i', 45,
        'l', 35,
        'm', 33,
        'n', 48,
        '}', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(71);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(57);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'g') ADVANCE(67);
      END_STATE();
    case 12:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(14);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(18);
      if (lookahead == 'x') ADVANCE(24);
      if (lookahead == '\r' ||
          lookahead == '?') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(64);
      if (lookahead != 0) ADVANCE(61);
      END_STATE();
    case 18:
      if (lookahead == '{') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == '|') ADVANCE(78);
      END_STATE();
    case 20:
      if (lookahead == '}') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 25:
      if (eof) ADVANCE(27);
      ADVANCE_MAP(
        '!', 8,
        '&', 2,
        '\'', 71,
        '(', 74,
        ')', 75,
        '*', 79,
        ',', 69,
        '-', 7,
        '.', 72,
        ':', 70,
        ';', 31,
        '=', 56,
        '>', 80,
        '[', 81,
        ']', 82,
        'f', 44,
        'i', 45,
        'l', 35,
        'm', 33,
        'n', 48,
        '{', 29,
        '|', 19,
        '}', 32,
        '~', 58,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 26:
      if (eof) ADVANCE(27);
      if (lookahead == '*') ADVANCE(79);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == 'f') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x2028 &&
          lookahead != 0x2029) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(30);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'h') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_unescaped_single_string_fragment);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_unescaped_single_string_fragment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (lookahead == '\n' ||
          lookahead == 0x2028 ||
          lookahead == 0x2029) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(61);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_inheriting);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_matching);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_matching);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_universal_selector);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 26},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 26},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 26},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 26},
  [43] = {.lex_state = 26},
  [44] = {.lex_state = 26},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 26},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 26},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 26},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 26},
  [60] = {.lex_state = 26},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 5},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 3},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 3},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 3},
  [112] = {.lex_state = 3},
  [113] = {.lex_state = 3},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 14},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 14},
  [121] = {.lex_state = 14},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 3},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 14},
  [127] = {.lex_state = 3},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 3},
  [131] = {.lex_state = 3},
  [132] = {.lex_state = 14},
  [133] = {.lex_state = 14},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_inheriting] = ACTIONS(1),
    [anon_sym_matching] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [sym_universal_selector] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(115),
    [sym_query] = STATE(18),
    [sym_function_declaration] = STATE(18),
    [sym__selector] = STATE(100),
    [sym_child_selector] = STATE(100),
    [sym_attribute_selector] = STATE(100),
    [aux_sym_source_file_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [sym_universal_selector] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      anon_sym_inheriting,
    ACTIONS(23), 1,
      anon_sym_matching,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_not,
    ACTIONS(33), 1,
      sym_universal_selector,
    STATE(3), 1,
      aux_sym_query_repeat1,
    STATE(104), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
    STATE(47), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
    STATE(71), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(98), 5,
      sym_query,
      sym_lexical_binding,
      sym_lexical_binding_inheritance,
      sym_function_match,
      sym_condition,
  [61] = 16,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      anon_sym_inheriting,
    ACTIONS(23), 1,
      anon_sym_matching,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_not,
    ACTIONS(33), 1,
      sym_universal_selector,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_query_repeat1,
    STATE(104), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
    STATE(47), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
    STATE(71), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(98), 5,
      sym_query,
      sym_lexical_binding,
      sym_lexical_binding_inheritance,
      sym_function_match,
      sym_condition,
  [122] = 16,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    ACTIONS(42), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_let,
    ACTIONS(48), 1,
      anon_sym_inheriting,
    ACTIONS(51), 1,
      anon_sym_matching,
    ACTIONS(54), 1,
      anon_sym_SQUOTE,
    ACTIONS(57), 1,
      anon_sym_DOT,
    ACTIONS(60), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_not,
    ACTIONS(66), 1,
      sym_universal_selector,
    STATE(4), 1,
      aux_sym_query_repeat1,
    STATE(104), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
    STATE(47), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
    STATE(71), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(98), 5,
      sym_query,
      sym_lexical_binding,
      sym_lexical_binding_inheritance,
      sym_function_match,
      sym_condition,
  [183] = 16,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      anon_sym_inheriting,
    ACTIONS(23), 1,
      anon_sym_matching,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_not,
    ACTIONS(33), 1,
      sym_universal_selector,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      aux_sym_query_repeat1,
    STATE(104), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
    STATE(47), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
    STATE(71), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(98), 5,
      sym_query,
      sym_lexical_binding,
      sym_lexical_binding_inheritance,
      sym_function_match,
      sym_condition,
  [244] = 16,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      anon_sym_inheriting,
    ACTIONS(23), 1,
      anon_sym_matching,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_not,
    ACTIONS(33), 1,
      sym_universal_selector,
    ACTIONS(71), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_query_repeat1,
    STATE(104), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
    STATE(47), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
    STATE(71), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(98), 5,
      sym_query,
      sym_lexical_binding,
      sym_lexical_binding_inheritance,
      sym_function_match,
      sym_condition,
  [305] = 16,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      anon_sym_inheriting,
    ACTIONS(23), 1,
      anon_sym_matching,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_not,
    ACTIONS(33), 1,
      sym_universal_selector,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_query_repeat1,
    STATE(104), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
    STATE(47), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
    STATE(71), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(98), 5,
      sym_query,
      sym_lexical_binding,
      sym_lexical_binding_inheritance,
      sym_function_match,
      sym_condition,
  [366] = 16,
    ACTIONS(13), 1,
      sym_comment,
    ACTIONS(17), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_let,
    ACTIONS(21), 1,
      anon_sym_inheriting,
    ACTIONS(23), 1,
      anon_sym_matching,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_not,
    ACTIONS(33), 1,
      sym_universal_selector,
    ACTIONS(75), 1,
      anon_sym_RBRACE,
    STATE(7), 1,
      aux_sym_query_repeat1,
    STATE(104), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
    STATE(47), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
    STATE(71), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(98), 5,
      sym_query,
      sym_lexical_binding,
      sym_lexical_binding_inheritance,
      sym_function_match,
      sym_condition,
  [427] = 6,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    STATE(61), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(91), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
  [452] = 6,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    STATE(61), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(74), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
  [477] = 6,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      sym_identifier,
    STATE(57), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
    STATE(71), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
  [502] = 6,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      sym_identifier,
    STATE(58), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
    STATE(71), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
  [527] = 6,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    STATE(61), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(69), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
  [552] = 6,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    STATE(61), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(68), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
  [577] = 6,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    STATE(61), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
    STATE(99), 4,
      sym__condition,
      sym_and_condition,
      sym_or_condition,
      sym_attribute_condition,
  [602] = 7,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_identifier,
    ACTIONS(89), 1,
      anon_sym_fn,
    ACTIONS(92), 1,
      sym_universal_selector,
    STATE(16), 3,
      sym_query,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
    STATE(100), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [628] = 2,
    ACTIONS(97), 5,
      sym_identifier,
      anon_sym_let,
      anon_sym_inheriting,
      anon_sym_matching,
      anon_sym_not,
    ACTIONS(95), 6,
      sym_comment,
      anon_sym_RBRACE,
      anon_sym_SQUOTE,
      anon_sym_DOT,
      anon_sym_LPAREN,
      sym_universal_selector,
  [644] = 7,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(11), 1,
      sym_universal_selector,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      sym_comment,
    STATE(16), 3,
      sym_query,
      sym_function_declaration,
      aux_sym_source_file_repeat1,
    STATE(100), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [670] = 2,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 8,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [684] = 5,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
    STATE(101), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
  [703] = 5,
    ACTIONS(109), 1,
      anon_sym_RBRACE,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(113), 1,
      sym_universal_selector,
    STATE(26), 2,
      sym_query,
      aux_sym_function_declaration_repeat2,
    STATE(105), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [722] = 5,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(113), 1,
      sym_universal_selector,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(26), 2,
      sym_query,
      aux_sym_function_declaration_repeat2,
    STATE(105), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [741] = 1,
    ACTIONS(117), 8,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [752] = 5,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(113), 1,
      sym_universal_selector,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(26), 2,
      sym_query,
      aux_sym_function_declaration_repeat2,
    STATE(105), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [771] = 5,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(113), 1,
      sym_universal_selector,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(22), 2,
      sym_query,
      aux_sym_function_declaration_repeat2,
    STATE(105), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [790] = 5,
    ACTIONS(123), 1,
      anon_sym_RBRACE,
    ACTIONS(125), 1,
      sym_identifier,
    ACTIONS(128), 1,
      sym_universal_selector,
    STATE(26), 2,
      sym_query,
      aux_sym_function_declaration_repeat2,
    STATE(105), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [809] = 1,
    ACTIONS(131), 8,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [820] = 1,
    ACTIONS(133), 8,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [831] = 5,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    STATE(97), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
  [850] = 5,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(113), 1,
      sym_universal_selector,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(21), 2,
      sym_query,
      aux_sym_function_declaration_repeat2,
    STATE(105), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [869] = 1,
    ACTIONS(139), 8,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [880] = 1,
    ACTIONS(141), 8,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [891] = 1,
    ACTIONS(143), 8,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [902] = 5,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(113), 1,
      sym_universal_selector,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(24), 2,
      sym_query,
      aux_sym_function_declaration_repeat2,
    STATE(105), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [921] = 4,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_identifier,
    STATE(114), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
  [937] = 4,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_DOT,
    ACTIONS(77), 1,
      sym_identifier,
    STATE(67), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
  [953] = 4,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(149), 1,
      anon_sym_SQUOTE,
    ACTIONS(151), 1,
      anon_sym_DOT,
    STATE(55), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
  [969] = 3,
    ACTIONS(105), 1,
      anon_sym_LPAREN,
    ACTIONS(103), 3,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
    ACTIONS(153), 3,
      anon_sym_LBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
  [983] = 4,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(149), 1,
      anon_sym_SQUOTE,
    ACTIONS(151), 1,
      anon_sym_DOT,
    STATE(77), 4,
      sym_string_literal,
      sym__expression,
      sym_attribute_identifier,
      sym_function_call,
  [999] = 2,
    ACTIONS(157), 1,
      anon_sym_LPAREN,
    ACTIONS(155), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1010] = 1,
    ACTIONS(159), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1018] = 2,
    ACTIONS(163), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(161), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_universal_selector,
  [1028] = 2,
    ACTIONS(167), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(165), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_universal_selector,
  [1038] = 2,
    ACTIONS(171), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(169), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_universal_selector,
  [1048] = 1,
    ACTIONS(173), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1056] = 1,
    ACTIONS(175), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1064] = 3,
    ACTIONS(179), 1,
      anon_sym_AMP_AMP,
    ACTIONS(181), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(177), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
  [1076] = 1,
    ACTIONS(183), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1084] = 2,
    ACTIONS(187), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(185), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_universal_selector,
  [1094] = 1,
    ACTIONS(189), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1102] = 1,
    ACTIONS(191), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1110] = 3,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(193), 1,
      sym_universal_selector,
    STATE(81), 3,
      sym__selector,
      sym_child_selector,
      sym_attribute_selector,
  [1122] = 2,
    ACTIONS(197), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(195), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_universal_selector,
  [1132] = 1,
    ACTIONS(199), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1140] = 1,
    ACTIONS(201), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1148] = 2,
    ACTIONS(205), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(203), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_universal_selector,
  [1158] = 1,
    ACTIONS(207), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1166] = 1,
    ACTIONS(209), 5,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
  [1174] = 2,
    ACTIONS(213), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(211), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_universal_selector,
  [1184] = 2,
    ACTIONS(217), 2,
      sym_identifier,
      anon_sym_fn,
    ACTIONS(215), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym_universal_selector,
  [1194] = 2,
    STATE(36), 1,
      sym_attribute_relation,
    ACTIONS(219), 3,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
  [1203] = 3,
    ACTIONS(224), 1,
      anon_sym_SQUOTE,
    STATE(62), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(221), 2,
      sym_unescaped_single_string_fragment,
      sym_escape_sequence,
  [1214] = 3,
    ACTIONS(228), 1,
      anon_sym_SQUOTE,
    STATE(62), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(226), 2,
      sym_unescaped_single_string_fragment,
      sym_escape_sequence,
  [1225] = 4,
    ACTIONS(230), 1,
      anon_sym_LBRACE,
    ACTIONS(232), 1,
      sym_identifier,
    STATE(117), 1,
      sym_object_pattern,
    STATE(121), 1,
      sym_variable_declarator,
  [1238] = 3,
    ACTIONS(236), 1,
      anon_sym_SQUOTE,
    STATE(63), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(234), 2,
      sym_unescaped_single_string_fragment,
      sym_escape_sequence,
  [1249] = 1,
    ACTIONS(238), 4,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [1256] = 1,
    ACTIONS(240), 4,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [1263] = 1,
    ACTIONS(242), 4,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [1270] = 1,
    ACTIONS(244), 4,
      anon_sym_RPAREN,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_RBRACK,
  [1277] = 3,
    ACTIONS(248), 1,
      anon_sym_SQUOTE,
    STATE(72), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(246), 2,
      sym_unescaped_single_string_fragment,
      sym_escape_sequence,
  [1288] = 2,
    STATE(37), 1,
      sym_attribute_relation,
    ACTIONS(219), 3,
      anon_sym_EQ,
      anon_sym_BANG_EQ,
      anon_sym_TILDE,
  [1297] = 3,
    ACTIONS(250), 1,
      anon_sym_SQUOTE,
    STATE(62), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(226), 2,
      sym_unescaped_single_string_fragment,
      sym_escape_sequence,
  [1308] = 4,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_COLON,
    STATE(78), 1,
      aux_sym_object_pattern_repeat1,
  [1321] = 3,
    ACTIONS(258), 1,
      anon_sym_RPAREN,
    ACTIONS(260), 1,
      anon_sym_AMP_AMP,
    ACTIONS(262), 1,
      anon_sym_PIPE_PIPE,
  [1331] = 3,
    ACTIONS(264), 1,
      anon_sym_RBRACE,
    ACTIONS(266), 1,
      sym_identifier,
    STATE(103), 1,
      sym_pair_pattern,
  [1341] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_function_call_repeat1,
  [1351] = 1,
    ACTIONS(272), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
  [1357] = 3,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
    STATE(84), 1,
      aux_sym_object_pattern_repeat1,
  [1367] = 1,
    ACTIONS(276), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
  [1373] = 1,
    ACTIONS(278), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
  [1379] = 1,
    ACTIONS(280), 3,
      anon_sym_LBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
  [1385] = 3,
    ACTIONS(282), 1,
      anon_sym_COMMA,
    ACTIONS(285), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_function_call_repeat1,
  [1395] = 2,
    ACTIONS(256), 1,
      anon_sym_COLON,
    ACTIONS(287), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1403] = 3,
    ACTIONS(287), 1,
      anon_sym_RBRACE,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    STATE(84), 1,
      aux_sym_object_pattern_repeat1,
  [1413] = 1,
    ACTIONS(153), 3,
      anon_sym_LBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
  [1419] = 1,
    ACTIONS(292), 3,
      sym_identifier,
      anon_sym_SQUOTE,
      anon_sym_DOT,
  [1425] = 1,
    ACTIONS(163), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
  [1431] = 1,
    ACTIONS(294), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
  [1437] = 1,
    ACTIONS(187), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
  [1443] = 1,
    ACTIONS(296), 3,
      anon_sym_LBRACE,
      anon_sym_GT,
      anon_sym_LBRACK,
  [1449] = 3,
    ACTIONS(260), 1,
      anon_sym_AMP_AMP,
    ACTIONS(262), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(298), 1,
      anon_sym_RBRACK,
  [1459] = 3,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
    STATE(95), 1,
      aux_sym_function_declaration_repeat1,
  [1469] = 1,
    ACTIONS(161), 3,
      anon_sym_RBRACE,
      sym_identifier,
      sym_universal_selector,
  [1475] = 1,
    ACTIONS(185), 3,
      anon_sym_RBRACE,
      sym_identifier,
      sym_universal_selector,
  [1481] = 3,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_function_declaration_repeat1,
  [1491] = 3,
    ACTIONS(306), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_function_declaration_repeat1,
  [1501] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
    STATE(76), 1,
      aux_sym_function_call_repeat1,
  [1511] = 1,
    ACTIONS(313), 3,
      anon_sym_LF,
      anon_sym_CR_LF,
      anon_sym_SEMI,
  [1517] = 3,
    ACTIONS(260), 1,
      anon_sym_AMP_AMP,
    ACTIONS(262), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(315), 1,
      anon_sym_RPAREN,
  [1527] = 3,
    ACTIONS(317), 1,
      anon_sym_LBRACE,
    ACTIONS(319), 1,
      anon_sym_GT,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
  [1537] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(323), 1,
      anon_sym_RPAREN,
    STATE(102), 1,
      aux_sym_function_call_repeat1,
  [1547] = 3,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(325), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_function_call_repeat1,
  [1557] = 3,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
    ACTIONS(254), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_object_pattern_repeat1,
  [1567] = 3,
    ACTIONS(319), 1,
      anon_sym_GT,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(327), 1,
      anon_sym_LBRACE,
  [1577] = 3,
    ACTIONS(319), 1,
      anon_sym_GT,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(329), 1,
      anon_sym_LBRACE,
  [1587] = 2,
    ACTIONS(331), 1,
      sym_identifier,
    STATE(80), 1,
      sym_function_call,
  [1594] = 1,
    ACTIONS(333), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1599] = 2,
    ACTIONS(335), 1,
      sym_identifier,
    STATE(109), 1,
      sym_pair_pattern,
  [1606] = 1,
    ACTIONS(287), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1611] = 1,
    ACTIONS(337), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [1616] = 2,
    ACTIONS(331), 1,
      sym_identifier,
    STATE(79), 1,
      sym_function_call,
  [1623] = 2,
    ACTIONS(339), 1,
      sym_identifier,
    ACTIONS(341), 1,
      anon_sym_RPAREN,
  [1630] = 2,
    ACTIONS(331), 1,
      sym_identifier,
    STATE(88), 1,
      sym_function_call,
  [1637] = 1,
    ACTIONS(285), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1642] = 1,
    ACTIONS(343), 1,
      ts_builtin_sym_end,
  [1646] = 1,
    ACTIONS(345), 1,
      anon_sym_LBRACE,
  [1650] = 1,
    ACTIONS(347), 1,
      anon_sym_matching,
  [1654] = 1,
    ACTIONS(349), 1,
      anon_sym_LBRACE,
  [1658] = 1,
    ACTIONS(351), 1,
      sym_identifier,
  [1662] = 1,
    ACTIONS(353), 1,
      anon_sym_matching,
  [1666] = 1,
    ACTIONS(355), 1,
      anon_sym_matching,
  [1670] = 1,
    ACTIONS(357), 1,
      anon_sym_LBRACE,
  [1674] = 1,
    ACTIONS(359), 1,
      sym_identifier,
  [1678] = 1,
    ACTIONS(361), 1,
      anon_sym_LPAREN,
  [1682] = 1,
    ACTIONS(363), 1,
      sym_identifier,
  [1686] = 1,
    ACTIONS(365), 1,
      anon_sym_matching,
  [1690] = 1,
    ACTIONS(367), 1,
      sym_identifier,
  [1694] = 1,
    ACTIONS(369), 1,
      anon_sym_EQ,
  [1698] = 1,
    ACTIONS(371), 1,
      anon_sym_LPAREN,
  [1702] = 1,
    ACTIONS(373), 1,
      sym_identifier,
  [1706] = 1,
    ACTIONS(375), 1,
      sym_identifier,
  [1710] = 1,
    ACTIONS(377), 1,
      anon_sym_matching,
  [1714] = 1,
    ACTIONS(379), 1,
      anon_sym_matching,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 122,
  [SMALL_STATE(5)] = 183,
  [SMALL_STATE(6)] = 244,
  [SMALL_STATE(7)] = 305,
  [SMALL_STATE(8)] = 366,
  [SMALL_STATE(9)] = 427,
  [SMALL_STATE(10)] = 452,
  [SMALL_STATE(11)] = 477,
  [SMALL_STATE(12)] = 502,
  [SMALL_STATE(13)] = 527,
  [SMALL_STATE(14)] = 552,
  [SMALL_STATE(15)] = 577,
  [SMALL_STATE(16)] = 602,
  [SMALL_STATE(17)] = 628,
  [SMALL_STATE(18)] = 644,
  [SMALL_STATE(19)] = 670,
  [SMALL_STATE(20)] = 684,
  [SMALL_STATE(21)] = 703,
  [SMALL_STATE(22)] = 722,
  [SMALL_STATE(23)] = 741,
  [SMALL_STATE(24)] = 752,
  [SMALL_STATE(25)] = 771,
  [SMALL_STATE(26)] = 790,
  [SMALL_STATE(27)] = 809,
  [SMALL_STATE(28)] = 820,
  [SMALL_STATE(29)] = 831,
  [SMALL_STATE(30)] = 850,
  [SMALL_STATE(31)] = 869,
  [SMALL_STATE(32)] = 880,
  [SMALL_STATE(33)] = 891,
  [SMALL_STATE(34)] = 902,
  [SMALL_STATE(35)] = 921,
  [SMALL_STATE(36)] = 937,
  [SMALL_STATE(37)] = 953,
  [SMALL_STATE(38)] = 969,
  [SMALL_STATE(39)] = 983,
  [SMALL_STATE(40)] = 999,
  [SMALL_STATE(41)] = 1010,
  [SMALL_STATE(42)] = 1018,
  [SMALL_STATE(43)] = 1028,
  [SMALL_STATE(44)] = 1038,
  [SMALL_STATE(45)] = 1048,
  [SMALL_STATE(46)] = 1056,
  [SMALL_STATE(47)] = 1064,
  [SMALL_STATE(48)] = 1076,
  [SMALL_STATE(49)] = 1084,
  [SMALL_STATE(50)] = 1094,
  [SMALL_STATE(51)] = 1102,
  [SMALL_STATE(52)] = 1110,
  [SMALL_STATE(53)] = 1122,
  [SMALL_STATE(54)] = 1132,
  [SMALL_STATE(55)] = 1140,
  [SMALL_STATE(56)] = 1148,
  [SMALL_STATE(57)] = 1158,
  [SMALL_STATE(58)] = 1166,
  [SMALL_STATE(59)] = 1174,
  [SMALL_STATE(60)] = 1184,
  [SMALL_STATE(61)] = 1194,
  [SMALL_STATE(62)] = 1203,
  [SMALL_STATE(63)] = 1214,
  [SMALL_STATE(64)] = 1225,
  [SMALL_STATE(65)] = 1238,
  [SMALL_STATE(66)] = 1249,
  [SMALL_STATE(67)] = 1256,
  [SMALL_STATE(68)] = 1263,
  [SMALL_STATE(69)] = 1270,
  [SMALL_STATE(70)] = 1277,
  [SMALL_STATE(71)] = 1288,
  [SMALL_STATE(72)] = 1297,
  [SMALL_STATE(73)] = 1308,
  [SMALL_STATE(74)] = 1321,
  [SMALL_STATE(75)] = 1331,
  [SMALL_STATE(76)] = 1341,
  [SMALL_STATE(77)] = 1351,
  [SMALL_STATE(78)] = 1357,
  [SMALL_STATE(79)] = 1367,
  [SMALL_STATE(80)] = 1373,
  [SMALL_STATE(81)] = 1379,
  [SMALL_STATE(82)] = 1385,
  [SMALL_STATE(83)] = 1395,
  [SMALL_STATE(84)] = 1403,
  [SMALL_STATE(85)] = 1413,
  [SMALL_STATE(86)] = 1419,
  [SMALL_STATE(87)] = 1425,
  [SMALL_STATE(88)] = 1431,
  [SMALL_STATE(89)] = 1437,
  [SMALL_STATE(90)] = 1443,
  [SMALL_STATE(91)] = 1449,
  [SMALL_STATE(92)] = 1459,
  [SMALL_STATE(93)] = 1469,
  [SMALL_STATE(94)] = 1475,
  [SMALL_STATE(95)] = 1481,
  [SMALL_STATE(96)] = 1491,
  [SMALL_STATE(97)] = 1501,
  [SMALL_STATE(98)] = 1511,
  [SMALL_STATE(99)] = 1517,
  [SMALL_STATE(100)] = 1527,
  [SMALL_STATE(101)] = 1537,
  [SMALL_STATE(102)] = 1547,
  [SMALL_STATE(103)] = 1557,
  [SMALL_STATE(104)] = 1567,
  [SMALL_STATE(105)] = 1577,
  [SMALL_STATE(106)] = 1587,
  [SMALL_STATE(107)] = 1594,
  [SMALL_STATE(108)] = 1599,
  [SMALL_STATE(109)] = 1606,
  [SMALL_STATE(110)] = 1611,
  [SMALL_STATE(111)] = 1616,
  [SMALL_STATE(112)] = 1623,
  [SMALL_STATE(113)] = 1630,
  [SMALL_STATE(114)] = 1637,
  [SMALL_STATE(115)] = 1642,
  [SMALL_STATE(116)] = 1646,
  [SMALL_STATE(117)] = 1650,
  [SMALL_STATE(118)] = 1654,
  [SMALL_STATE(119)] = 1658,
  [SMALL_STATE(120)] = 1662,
  [SMALL_STATE(121)] = 1666,
  [SMALL_STATE(122)] = 1670,
  [SMALL_STATE(123)] = 1674,
  [SMALL_STATE(124)] = 1678,
  [SMALL_STATE(125)] = 1682,
  [SMALL_STATE(126)] = 1686,
  [SMALL_STATE(127)] = 1690,
  [SMALL_STATE(128)] = 1694,
  [SMALL_STATE(129)] = 1698,
  [SMALL_STATE(130)] = 1702,
  [SMALL_STATE(131)] = 1706,
  [SMALL_STATE(132)] = 1710,
  [SMALL_STATE(133)] = 1714,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(98),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(38),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(130),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(64),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(106),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(65),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(131),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(10),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(132),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 9), SHIFT_REPEAT(104),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(125),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2, 0, 6),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_query_repeat1, 2, 0, 6),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 17),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat2, 2, 0, 0),
  [125] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(85),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat2, 2, 0, 0), SHIFT_REPEAT(105),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, 0, 21),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_identifier, 2, 0, 7),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 11),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 12),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__selector, 1, 0, 1),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 3),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 3, 0, 12),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 3, 0, 2),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query, 3, 0, 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 9, 0, 23),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 9, 0, 23),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 6, 0, 16),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 6, 0, 16),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_identifier, 2, 0, 7),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1, 0, 4),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 11),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 4, 0, 8),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_query, 4, 0, 8),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 17),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, 0, 21),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 7, 0, 20),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 7, 0, 20),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__condition, 3, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute_condition, 3, 0, 13),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 7, 0, 16),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 7, 0, 16),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_and_condition, 3, 0, 14),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_or_condition, 3, 0, 14),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 8, 0, 20),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 8, 0, 20),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_declaration, 8, 0, 23),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_declaration, 8, 0, 23),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [221] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__condition, 3, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_condition, 3, 0, 13),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and_condition, 3, 0, 14),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_condition, 3, 0, 14),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lexical_binding, 4, 0, 18),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [276] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lexical_binding_inheritance, 4, 0, 19),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_match, 2, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_child_selector, 3, 0, 5),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_pattern_repeat1, 2, 0, 0),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_pattern_repeat1, 2, 0, 0), SHIFT_REPEAT(108),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_relation, 1, 0, 0),
  [294] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_match, 3, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_selector, 4, 0, 10),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [306] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 0),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [313] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [333] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_declaration_repeat1, 2, 0, 15),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair_pattern, 3, 0, 22),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [343] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_declarator, 1, 0, 0),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_pattern, 4, 0, 0),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [365] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_pattern, 2, 0, 0),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_pattern, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tql(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tql",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
