packages:
  - packages/playground
  - packages/tql-js
  - packages/tree-sitter-tql

onlyBuiltDependencies:
  - esbuild
  - tree-sitter
  - tree-sitter-c
  - tree-sitter-cli
  - tree-sitter-cpp
  - tree-sitter-go
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-rust
  - tree-sitter-typescript
  - tree-sitter-zig
