packages:
  - packages/playground
  - packages/tql-js
  # getting installation errors if i try to add this
  # - packages/tree-sitter-tql

onlyBuiltDependencies:
  - tree-sitter
  - tree-sitter-cli
  - tree-sitter-javascript
  - esbuild
