version: "3"

tasks:
  default:
    cmds:
      - task --list

  build:
    cmds: [pnpm run build]

  serve:
    deps: [build]
    cmds: ["python -m http.server 8000 -d build"]

  dev:
    cmds: [pnpm run dev]

  check:
    cmds: [pnpm run check]

  clean:
    cmds:
      - rm -rf node_modules build
      - rm -f static/tree-sitter-*.wasm static/tql.wasm
