version: "3"

tasks:
  default: task --list

  build-cli:
    vars:
      ARGS: '{{.CLI_ARGS | default "-Dgrammars=available"}}'
    cmd: zig build {{.ARGS}}

  build-wasm:
    vars:
      ARGS: '{{.CLI_ARGS | default "-Dgrammars=available"}}'
    cmd: zig build wasm {{.ARGS}}

  build-grammars:
    vars:
      ARGS: '{{.CLI_ARGS | default "-Dgrammars=available"}}'
    cmd: zig build grammars {{.ARGS}}

  build:
    vars:
      ARGS: '{{.CLI_ARGS | default "-Dgrammars=available"}}'
    deps:
      - task: build-cli
        vars:
          ARGS: "{{.ARGS}}"
      - task: build-wasm
        vars:
          ARGS: "{{.ARGS}}"
      - task: build-grammars
        vars:
          ARGS: "{{.ARGS}}"

  release: zig build -Doptimize=ReleaseFast --release=fast

  snapshot-test: zig build snapshot-test

  root-test: zig build test

  test:
    deps: [root-test, snapshot-test]

  run: zig build run -- {{.CLI_ARGS}}

  fmt: zig fmt src tests build.zig

  clean: rm -rf zig-out .zig-cache
