//! A linked Core program: what desugaring produces and every later stage
//! reads.

const std = @import("std");
const core = @import("../core.zig");

/// A linked program: definitions, the SCCs type checking consumes, and the
/// entrypoint.
///
/// Terms and the strings they reference live in `arena`, which is heap-owned so
/// the program can be returned by value: an `ArenaAllocator`'s allocator holds
/// a pointer to the arena itself, which moving the struct would dangle.
pub const Program = struct {
    /// Symbols, declared types, and what passes have learned about them.
    /// Owns the arena every definition is allocated from.
    env: core.env.Env,
    definitions: []const core.Definition,
    /// Indices into `definitions`, grouped by strongly connected component in
    /// dependency order. A reference to a definition with a signature is not
    /// a dependency. Empty once simplification drops a definition.
    components: []const []const u32,
    /// The linked program's `main`.
    entry: core.SymbolId,
    /// Where the entry module's definitions begin; everything below it was
    /// linked in from a library module.
    entry_offset: u32,
    /// Where the entry module's definitions end; everything from here on was
    /// generated by type checking.
    entry_end: u32,

    /// The definitions the entry module declared, in declaration order, its
    /// instance methods included.
    pub fn entryDefinitions(self: *const Program) []const core.Definition {
        return self.definitions[self.entry_offset..self.entry_end];
    }

    pub fn deinit(self: *Program) void {
        self.env.deinit();
    }

    /// The entry module's definitions less its instances' methods, which
    /// it defines but never names.
    pub fn namedDefinitions(self: *const Program) NamedDefinitions {
        return .{ .interner = &self.env.interner, .rest = self.entryDefinitions() };
    }

    pub const NamedDefinitions = struct {
        interner: *const core.Interner,
        rest: []const core.Definition,

        pub fn next(self: *NamedDefinitions) ?core.Definition {
            while (self.rest.len > 0) {
                const d = self.rest[0];
                self.rest = self.rest[1..];
                if (self.interner.details(d.symbol) != .instance_method) return d;
            }
            return null;
        }
    };
};

/// One `name = term` line per definition the entry module declared, in
/// declaration order. Library definitions linked in beneath it, and
/// definitions generated for instances, are omitted.
pub fn printProgram(
    p: *const Program,
    w: *std.Io.Writer,
) std.Io.Writer.Error!void {
    const printer: core.Printer = .{ .interner = &p.env.interner };
    var first = true;
    var named = p.namedDefinitions();
    while (named.next()) |d| {
        if (!first) try w.writeByte('\n');
        first = false;
        try printer.definition(d.symbol, d.body, w);
    }
}
